server:
    port: 80

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/FinanceBOT
        username: admin
        password: 0852
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
                show_sql: true
        hibernate:
            ddl-auto: update
jwt:
    token:
        secret: doniksecretkey123
        validity: 21600000